export const GET_ALBUM = 'GET_ALBUM';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAILURE = 'GET_ALBUM_FAILURE';

export const GET_ALBUMS = 'GET_ALBUMS';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILURE = 'GET_ALBUMS_FAILURE';

export const GET_ALBUM_PHOTOS = 'GET_ALBUM_PHOTOS';
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCCESS';
export const GET_ALBUM_PHOTOS_FAILURE = 'GET_ALBUM_PHOTOS_FAILURE';

export const OPEN_DETAILS_DIALOG = 'OPEN_DETAILS_DIALOG';
export const CLOSE_DETAILS_DIALOG = 'CLOSE_DETAILS_DIALOG';
export const SET_DETAILS_PHOTO = 'SET_DETAILS_PHOTO';
